New tip for demand graph in EIA (US Energy) example
observablehq/framework pull request #1041
Opened 2024-03-12 00:09 UTC by pettiross

Replaces default tip for the three-line graph with an hourly summary so it's easier to read. Also changed to zip archive data loader to create 2 different levels of detail from a single web API call.

Apologies in advance for the rename of us-demand.csv.js to us-demand.zip.js not showing as a diff. I tried using both the `git mv` on the CLI and the GitHub UI to rename the file (see the 28 Feb commits), but if there was a way to make it work, I did not figure it out. 🤷

![image](https://github.com/observablehq/framework/assets/3514378/7da6ca5a-e7f6-4e2a-ae67-2af395cb5cd3)

2024-03-17 17:39 UTC, pettiross commented
Thanks for the comments, @Fil. As you suggested, I changed the data loader back to a single CSV and moved the rollup into the chart code (which also cleared up the need to deal with the rename). I also updated the date in the tooltip to be like "10 Mar" (which is how I tend to write dates personally anyway...).

2024-03-18 10:32 UTC, Fil approved these changes

2024-03-18 10:32 UTC, Fil commented on examples/eia/docs/components/charts.js
> +  })
```suggestion
  });
```

2024-03-18 10:32 UTC, Fil commented on examples/eia/docs/components/charts.js
> +  }, new Map())
```suggestion
  }, new Map());
```

2024-03-18 10:32 UTC, Fil commented on examples/eia/docs/components/charts.js
> +  rolledToHour.forEach((d) => { rolledUpSparse.push(d) });
```suggestion
  for (const d of rolledToHour) rolledUpSparse.push(d);
```

2024-03-18 10:32 UTC, Fil commented on examples/eia/docs/components/charts.js
> +      tickFormat: d => friendlyTypeName[d],
```suggestion
      tickFormat: (d) => friendlyTypeName[d],
```

2024-03-18 10:32 UTC, Fil commented on examples/eia/docs/components/charts.js
> +  })
```suggestion
  });
```

2024-03-18 10:32 UTC, Fil commented on examples/eia/docs/components/charts.js
> +  })
```suggestion
  });
```

2024-03-18 10:36 UTC, Fil requested changes
one sec, I need to test something

2024-03-18 10:47 UTC, Fil approved these changes

2024-03-18 10:50 UTC, merged

2024-03-18 10:57 UTC, Fil commented
it is now deployed https://observablehq.com/framework/examples/eia/

2024-03-18 15:35 UTC, pettiross commented
Thank you for the further edits, @Fil. I'm learning by reviewing what you did.