add support for java data loaders
observablehq/framework pull request #846
Opened 2024-02-17 11:03 UTC by cyrilou242

Add support for java data loaders as discussed here:
https://github.com/observablehq/framework/issues/831

I put a [ForecastJava.json.java](https://github.com/observablehq/framework/compare/main...cyrilou242:framework:main#diff-e5a7882f72679fb0b6628ef66848b4597d6eeaa55e6793b2ab79897491c16df7) to have an example of how to load json in java. It's not used anywhere but it's easy to try be replacing in the getting started 
```
const forecast = FileAttachment("./data/forecast.json").json();
```

by 
```
const forecast = FileAttachment("./data/ForecastJava.json").json();
```
Can be removed if it's not helpful.

2024-02-17 16:37 UTC, mbostock requested changes
Thanks for this! 🙏

2024-02-17 16:37 UTC, mbostock commented on docs/loaders.md
> +If you use `.py`, `.R`, `.rs`, `.go` or `java`, the corresponding interpreter (`python3`, `Rscript`, `rust-script`, `go run` or `java`, respectively) must be installed and available on your `$PATH`.
```suggestion
If you use `.py`, `.R`, `.rs`, `.go`, or `java`, the corresponding interpreter (`python3`, `Rscript`, `rust-script`, `go run`, or `java`, respectively) must be installed and available on your `$PATH`. Any additional modules, packages, libraries, _etc._, must also be installed before you can use them.
```

2024-02-17 16:37 UTC, mbostock commented on docs/loaders.md
> +Whereas `.js`, `.ts`, `.py`, `.R`, `.rs`, `.go`, `.java` and `.sh` data loaders are run via interpreters, `.exe` data loaders are run directly and must have the executable bit set. This is typically
```suggestion
Whereas all other data loaders are run via interpreters (such as `node` for `.js`), `.exe` data loaders are run directly and must have the executable bit set. This is typically done via [`chmod`](https://en.wikipedia.org/wiki/Chmod). For example:
```

I think we have enough data loaders now that it makes sense to refer to them in aggregate and only call out `.exe` is being special.

2024-02-17 16:37 UTC, mbostock commented on docs/loaders.md
> +- `.java` - Java >=11 (`java`)
```suggestion
- `.java` - Java (`java`; requires Java 11+ and [single-file programs](https://openjdk.org/jeps/330))
```

2024-02-17 16:37 UTC, mbostock commented on docs/HelloJava.txt.java
Can we rename this file to `hello-java.txt.java` to match the Go and Rust “hello world” loaders? I tested it and it appeared to work, but I don’t know if that’s a recent relaxation of naming constraints. I also tested making the class non-public (just `class HelloJava`) and that worked too, and I think that’s always be allowed.

2024-02-17 16:37 UTC, mbostock commented on docs/data/ForecastJava.json.java
Per the other comment, ideally this would be named `forecast.json.java` so that a Java data loader can serve the same `forecast.json` rather than revealing it’s Java-ness to the client.

2024-02-28 14:28 UTC, Fil commented
wrapped under #935

2024-03-12 20:57 UTC, Fil commented
solved in https://github.com/observablehq/framework/pull/935

2024-03-12 20:57 UTC, closed without merging

2024-03-19 12:20 UTC, cyrilou242 commented
Thanks for this!